import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1766050853132 implements MigrationInterface {
    name = 'Init1766050853132'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."patient_profiles_gender_enum" AS ENUM('NAM', 'NU', 'KHAC')`);
        await queryRunner.query(`CREATE TABLE "patient_profiles" ("patient_id" uuid NOT NULL, "full_name" character varying(255) NOT NULL, "dob" date NOT NULL, "gender" "public"."patient_profiles_gender_enum" NOT NULL, "address" text, "medical_history" text, "allergy_history" text, "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_93e9bd4212c9d779fb8b4398bd7" PRIMARY KEY ("patient_id"))`);
        await queryRunner.query(`CREATE TABLE "sys_users" ("user_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying(100), "password" character varying(255), "email" character varying(150), "phone" character varying(20), "cccd" character varying(12), "is_active" boolean NOT NULL DEFAULT true, "refresh_token_hash" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_466c22a61fbc6141d7b064cbed4" UNIQUE ("username"), CONSTRAINT "UQ_71f921cdd2a2d68e7825152c684" UNIQUE ("cccd"), CONSTRAINT "PK_360c27699169a865b1c7aa6f8d7" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_466c22a61fbc6141d7b064cbed" ON "sys_users" ("username") `);
        await queryRunner.query(`CREATE INDEX "IDX_71f921cdd2a2d68e7825152c68" ON "sys_users" ("cccd") `);
        await queryRunner.query(`CREATE TABLE "sys_roles" ("role_id" SERIAL NOT NULL, "role_code" character varying(50) NOT NULL, "role_name" character varying(100), "description" text, CONSTRAINT "UQ_d50f63eff3ee563a92cdca56bf6" UNIQUE ("role_code"), CONSTRAINT "PK_b94678bcefe1a557ed67613bbfa" PRIMARY KEY ("role_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."org_rooms_room_type_enum" AS ENUM('CLINIC', 'IMAGING', 'LAB', 'PHARMACY', 'CASHIER', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "org_rooms" ("room_id" SERIAL NOT NULL, "room_name" character varying(100) NOT NULL, "room_type" "public"."org_rooms_room_type_enum", "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_f76b9aae085d880b9b27ce208c8" PRIMARY KEY ("room_id"))`);
        await queryRunner.query(`CREATE TABLE "ref_specialties" ("specialty_id" SERIAL NOT NULL, "specialty_code" character varying(50) NOT NULL, "specialty_name" character varying(255) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_957c6df5382e1b12df47b51157f" UNIQUE ("specialty_code"), CONSTRAINT "PK_3efcc291a06a2f0e2ca2204e9c8" PRIMARY KEY ("specialty_id"))`);
        await queryRunner.query(`CREATE TABLE "staff_profiles" ("staff_id" uuid NOT NULL, "role_id" integer NOT NULL, "assigned_room_id" integer, "specialty_id" integer, "full_name" character varying(255) NOT NULL, "signature_url" character varying(500), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_4f32f1a897f75bafed4199fb0bf" PRIMARY KEY ("staff_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."system_notifications_notification_type_enum" AS ENUM('SYSTEM', 'APPOINTMENT', 'URGENT', 'LEAVE', 'PAYROLL', 'TASK')`);
        await queryRunner.query(`CREATE TABLE "system_notifications" ("notification_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "sender_id" uuid, "title" character varying(200) NOT NULL, "message" text NOT NULL, "notification_type" "public"."system_notifications_notification_type_enum" NOT NULL DEFAULT 'SYSTEM', "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "is_deleted" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_e5f653c46aaa7f7c013de4e6949" PRIMARY KEY ("notification_id"))`);
        await queryRunner.query(`CREATE TABLE "system_config" ("config_id" SERIAL NOT NULL, "updated_by" uuid, "config_key" character varying(100) NOT NULL, "config_value" character varying(500) NOT NULL, "config_type" character varying(50) NOT NULL DEFAULT 'GENERAL', "description" text, "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_c54d4e3d5a246ef29601e48d751" UNIQUE ("config_key"), CONSTRAINT "PK_49ea995519ff033fdbed374cdfb" PRIMARY KEY ("config_id"))`);
        await queryRunner.query(`CREATE TABLE "system_audit_logs" ("log_id" BIGSERIAL NOT NULL, "user_id" uuid, "action_type" character varying(50), "table_name" character varying(50), "record_id" character varying(50), "old_value" jsonb, "new_value" jsonb, "ip_address" inet, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_857440f1a83e764ef8149847a8e" PRIMARY KEY ("log_id"))`);
        await queryRunner.query(`CREATE TABLE "ref_icd10" ("icd_code" character varying(10) NOT NULL, "parent_code" character varying(10), "name_vi" character varying(500) NOT NULL, "name_en" character varying(500), "level" integer, "is_leaf" boolean NOT NULL DEFAULT false, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_ab183b9cc9e377cb84f114e7449" PRIMARY KEY ("icd_code"))`);
        await queryRunner.query(`CREATE TYPE "public"."medical_encounters_current_status_enum" AS ENUM('REGISTERED', 'AWAITING_PAYMENT', 'IN_CONSULTATION', 'AWAITING_CLS', 'IN_CLS', 'CLS_COMPLETED', 'RESULTS_READY', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "medical_encounters" ("encounter_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patient_id" uuid, "doctor_id" uuid, "assigned_room_id" integer, "final_icd_code" character varying(10), "visit_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "current_status" "public"."medical_encounters_current_status_enum" NOT NULL DEFAULT 'REGISTERED', "initial_symptoms" text, "weight" numeric(5,2), "height" numeric(5,2), "bmi" numeric(4,2), "temperature" numeric(4,1), "pulse" integer, "respiratory_rate" integer, "bp_systolic" integer, "bp_diastolic" integer, "sp_o2" numeric(5,2), "doctor_conclusion" text, "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_2a840667ef58abb1f90226ab28b" PRIMARY KEY ("encounter_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."service_requests_payment_status_enum" AS ENUM('UNPAID', 'PARTIALLY_PAID', 'PAID', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "service_requests" ("request_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "encounter_id" uuid, "requesting_doctor_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "payment_status" "public"."service_requests_payment_status_enum" NOT NULL DEFAULT 'UNPAID', "notes" text, "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_f01ec4a8e6bb19cc88f80aa835d" PRIMARY KEY ("request_id"))`);
        await queryRunner.query(`CREATE TABLE "ref_service_categories" ("category_id" SERIAL NOT NULL, "parent_id" integer, "category_name" character varying(255) NOT NULL, "is_system_root" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_9ff47e4cede15f0e081fc94265d" PRIMARY KEY ("category_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ref_services_result_input_type_enum" AS ENUM('NUMERIC', 'TEXT', 'NUMERIC_AND_TEXT', 'IMAGE_AND_TEXT')`);
        await queryRunner.query(`CREATE TABLE "ref_services" ("service_id" SERIAL NOT NULL, "category_id" integer, "service_name" character varying(255) NOT NULL, "unit_price" numeric(15,2), "result_input_type" "public"."ref_services_result_input_type_enum", CONSTRAINT "PK_ebbef22eb39f6d8ea2eb9cbbcc8" PRIMARY KEY ("service_id"))`);
        await queryRunner.query(`CREATE TABLE "service_request_items" ("item_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "request_id" uuid, "service_id" integer, CONSTRAINT "PK_8e7b53337e0bf4c0484e81dcd13" PRIMARY KEY ("item_id"))`);
        await queryRunner.query(`CREATE TABLE "service_report_templates" ("template_id" SERIAL NOT NULL, "service_id" integer, "created_by" uuid, "template_name" character varying(150) NOT NULL, "body_html" text NOT NULL, "is_default" boolean NOT NULL DEFAULT false, "is_public" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_40f54b74a458ed2c7b98efb1501" PRIMARY KEY ("template_id"))`);
        await queryRunner.query(`CREATE TABLE "service_results" ("result_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "request_item_id" uuid, "technician_id" uuid, "approving_doctor_id" uuid, "used_template_id" integer, "main_conclusion" text, "report_body_html" text, "is_abnormal" boolean NOT NULL DEFAULT false, "result_time" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_db0e4c29e1fd7b7a3b7a9ac7562" PRIMARY KEY ("result_id"))`);
        await queryRunner.query(`CREATE TABLE "result_discussions" ("discussion_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "result_id" uuid NOT NULL, "sender_id" uuid NOT NULL, "parent_id" uuid, "message_content" text NOT NULL, "lft" integer NOT NULL, "rgt" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c113c0ff1e094d7ca8c3f39c162" PRIMARY KEY ("discussion_id"))`);
        await queryRunner.query(`CREATE TABLE "room_services" ("room_id" integer NOT NULL, "service_id" integer NOT NULL, CONSTRAINT "PK_dac4ce50107d88ad7bce51fe61b" PRIMARY KEY ("room_id", "service_id"))`);
        await queryRunner.query(`CREATE TABLE "result_images" ("image_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "result_id" uuid, "uploaded_by" uuid, "public_id" character varying(255), "original_image_url" character varying(500) NOT NULL, "file_name" character varying(255), "file_size" bigint, "mime_type" character varying(100), "uploaded_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a746d6b44498251b6e9ca3fcc1a" PRIMARY KEY ("image_id"))`);
        await queryRunner.query(`CREATE TABLE "ref_lab_indicators" ("indicator_id" SERIAL NOT NULL, "indicator_code" character varying(50), "indicator_name" character varying(200) NOT NULL, "unit" character varying(50), "ref_min_male" numeric(10,4), "ref_max_male" numeric(10,4), "ref_min_female" numeric(10,4), "ref_max_female" numeric(10,4), CONSTRAINT "PK_1ca78f20538b4c413f5e0cd6f95" PRIMARY KEY ("indicator_id"))`);
        await queryRunner.query(`CREATE TABLE "rel_service_indicators" ("service_id" integer NOT NULL, "indicator_id" integer NOT NULL, "sort_order" integer, CONSTRAINT "PK_2fa81120f96d33d6561ccf6a4bf" PRIMARY KEY ("service_id", "indicator_id"))`);
        await queryRunner.query(`CREATE TABLE "result_details_numeric" ("detail_id" BIGSERIAL NOT NULL, "result_id" uuid, "indicator_id" integer, "value_measured" numeric(10,4), "is_critical" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_aec71f5c5ae8ce37d520c4bcbab" PRIMARY KEY ("detail_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."queue_tickets_ticket_type_enum" AS ENUM('REGISTRATION', 'CONSULTATION', 'SERVICE')`);
        await queryRunner.query(`CREATE TYPE "public"."queue_tickets_source_enum" AS ENUM('ONLINE', 'WALKIN')`);
        await queryRunner.query(`CREATE TYPE "public"."queue_tickets_status_enum" AS ENUM('WAITING', 'CALLED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED')`);
        await queryRunner.query(`CREATE TABLE "queue_tickets" ("ticket_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "encounter_id" uuid, "room_id" integer NOT NULL, "ticket_type" "public"."queue_tickets_ticket_type_enum" NOT NULL, "display_number" integer NOT NULL, "source" "public"."queue_tickets_source_enum" NOT NULL DEFAULT 'WALKIN', "status" "public"."queue_tickets_status_enum" NOT NULL DEFAULT 'WAITING', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "called_at" TIMESTAMP WITH TIME ZONE, "started_at" TIMESTAMP WITH TIME ZONE, "service_ids" integer array, "completed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_e573582e059b4043f3275aecead" PRIMARY KEY ("ticket_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."queue_counters_ticket_type_enum" AS ENUM('REGISTRATION', 'CONSULTATION', 'SERVICE')`);
        await queryRunner.query(`CREATE TABLE "queue_counters" ("counter_id" SERIAL NOT NULL, "room_id" integer NOT NULL, "ticket_type" "public"."queue_counters_ticket_type_enum" NOT NULL, "last_number" integer NOT NULL DEFAULT '0', "reset_date" date NOT NULL DEFAULT ('now'::text)::date, CONSTRAINT "PK_d55dbbc8a94c8f6b4ecf704e4e7" PRIMARY KEY ("counter_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_counter_room_type_day" ON "queue_counters" ("room_id", "ticket_type", "reset_date") `);
        await queryRunner.query(`CREATE TABLE "ref_drug_categories" ("category_id" SERIAL NOT NULL, "parent_id" integer, "category_code" character varying(20), "category_name" character varying(255) NOT NULL, CONSTRAINT "PK_2c2b8454715d3767cbf832ace84" PRIMARY KEY ("category_id"))`);
        await queryRunner.query(`CREATE TABLE "ref_drugs" ("drug_id" SERIAL NOT NULL, "category_id" integer, "drug_name" character varying(255) NOT NULL, "active_ingredient" character varying(255), "drug_code" character varying(50), "dosage_form" character varying(50), "route" character varying(50), "strength" character varying(50), "unit_name" character varying(50), "reorder_level" integer, "unit_price" numeric(10,2), "quantity" integer, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_f03a68ee2ba8619d9eee36042ff" UNIQUE ("drug_code"), CONSTRAINT "PK_f0c87ae5e3526d6527ab92b5ee0" PRIMARY KEY ("drug_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."prescriptions_status_enum" AS ENUM('DRAFT', 'ISSUED', 'DISPENSED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "prescriptions" ("prescription_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "encounter_id" uuid, "prescribing_doctor_id" uuid, "dispensing_pharmacist_id" uuid, "status" "public"."prescriptions_status_enum" NOT NULL DEFAULT 'DRAFT', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_88ae21471f1463e211b485dc205" PRIMARY KEY ("prescription_id"))`);
        await queryRunner.query(`CREATE TABLE "prescription_details" ("detail_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "prescription_id" uuid, "drug_id" integer, "quantity" integer NOT NULL, "usage_note" text, CONSTRAINT "PK_df490d21858a1d3fcfca8b69749" PRIMARY KEY ("detail_id"))`);
        await queryRunner.query(`CREATE TABLE "drug_imports" ("import_id" SERIAL NOT NULL, "imported_by" uuid, "import_date" date NOT NULL DEFAULT ('now'::text)::date, "total_amount" numeric(15,2), "invoice_number" character varying(100), "notes" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c341ad437524cc48e64f86f581b" PRIMARY KEY ("import_id"))`);
        await queryRunner.query(`CREATE TABLE "ref_payment_methods" ("payment_method_code" character varying(20) NOT NULL, "method_name" character varying(100) NOT NULL, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_eef84b05a2d9090242e964bc35d" PRIMARY KEY ("payment_method_code"))`);
        await queryRunner.query(`CREATE TABLE "drug_import_details" ("import_detail_id" SERIAL NOT NULL, "import_id" integer NOT NULL, "drug_id" integer NOT NULL, "batch_number" character varying(50), "expiry_date" date NOT NULL, "quantity" integer NOT NULL, "unit_price" numeric(10,2) NOT NULL, CONSTRAINT "PK_5622482c9a0b57853e3f0c60906" PRIMARY KEY ("import_detail_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('DRAFT', 'UNPAID', 'PARTIAL', 'PAID', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("invoice_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "encounter_id" uuid, "cashier_id" uuid, "total_amount" numeric(15,2), "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'UNPAID', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "payment_time" TIMESTAMP WITH TIME ZONE, "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_a62eb88a23934fb83945c3e58af" PRIMARY KEY ("invoice_id"))`);
        await queryRunner.query(`CREATE TABLE "invoice_payments" ("payment_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "invoice_id" uuid NOT NULL, "payment_method_code" character varying(20) NOT NULL, "amount" numeric(15,2) NOT NULL, "paid_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "transaction_ref" character varying(100), "notes" text, CONSTRAINT "PK_6cb266b357064c1de47fe2a1643" PRIMARY KEY ("payment_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."invoice_items_item_type_enum" AS ENUM('CONSULTATION', 'SERVICE', 'DRUG', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "invoice_items" ("invoice_item_id" BIGSERIAL NOT NULL, "invoice_id" uuid NOT NULL, "service_item_id" uuid, "prescription_detail_id" uuid, "item_type" "public"."invoice_items_item_type_enum" NOT NULL, "description" text, "quantity" integer NOT NULL, "unit_price" numeric(15,2) NOT NULL, "line_amount" numeric(15,2) NOT NULL, CONSTRAINT "PK_6ba01450ea6248cbd6f10de84bb" PRIMARY KEY ("invoice_item_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."image_annotations_annotation_source_enum" AS ENUM('AI', 'HUMAN')`);
        await queryRunner.query(`CREATE TYPE "public"."image_annotations_annotation_status_enum" AS ENUM('IN_PROGRESS', 'SUBMITTED', 'APPROVED', 'REJECTED', 'DEPRECATED')`);
        await queryRunner.query(`CREATE TABLE "image_annotations" ("annotation_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "image_id" uuid NOT NULL, "labeled_by" uuid, "reviewed_by" uuid, "approved_by" uuid, "annotation_source" "public"."image_annotations_annotation_source_enum" NOT NULL, "annotation_data" jsonb NOT NULL, "ai_model_name" character varying(100), "ai_model_version" character varying(50), "labeled_at" TIMESTAMP WITH TIME ZONE, "reviewed_at" TIMESTAMP WITH TIME ZONE, "approved_at" TIMESTAMP WITH TIME ZONE, "annotation_status" "public"."image_annotations_annotation_status_enum" NOT NULL DEFAULT 'IN_PROGRESS', "rejection_reason" text, "deprecation_reason" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_fb3df6efc4e13e2e9d35e97afbc" PRIMARY KEY ("annotation_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."annotation_projects_task_type_enum" AS ENUM('CLASSIFICATION', 'BOUNDING_BOX', 'SEGMENTATION', 'KEYPOINT', 'OCR', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "annotation_projects" ("project_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" uuid, "name" character varying(255) NOT NULL, "description" text, "task_type" "public"."annotation_projects_task_type_enum" NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bfcf1c8bb3fd31f0a23c7fe6ec" PRIMARY KEY ("project_id"))`);
        await queryRunner.query(`CREATE TABLE "annotation_project_images" ("project_id" uuid NOT NULL, "image_id" uuid NOT NULL, "added_by" uuid, "added_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d68f68a6f34f807a5e694943d84" PRIMARY KEY ("project_id", "image_id"))`);
        await queryRunner.query(`ALTER TABLE "patient_profiles" ADD CONSTRAINT "FK_93e9bd4212c9d779fb8b4398bd7" FOREIGN KEY ("patient_id") REFERENCES "sys_users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" ADD CONSTRAINT "FK_4f32f1a897f75bafed4199fb0bf" FOREIGN KEY ("staff_id") REFERENCES "sys_users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" ADD CONSTRAINT "FK_202fa10b67fa2a55f4c53b704ed" FOREIGN KEY ("role_id") REFERENCES "sys_roles"("role_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" ADD CONSTRAINT "FK_cb1a0b04899905a2d423ed4b2ee" FOREIGN KEY ("assigned_room_id") REFERENCES "org_rooms"("room_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" ADD CONSTRAINT "FK_3f82683aa41853a895289b18d0d" FOREIGN KEY ("specialty_id") REFERENCES "ref_specialties"("specialty_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system_notifications" ADD CONSTRAINT "FK_0d846fbfc20a6cb6fe06e61b41e" FOREIGN KEY ("user_id") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system_notifications" ADD CONSTRAINT "FK_4729e2a2eda3f5d226c5174e66f" FOREIGN KEY ("sender_id") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "system_config" ADD CONSTRAINT "FK_674473bbaa9859ba7e7d9f7ea9e" FOREIGN KEY ("updated_by") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ref_icd10" ADD CONSTRAINT "FK_1f8549d688a778e335445c7f43c" FOREIGN KEY ("parent_code") REFERENCES "ref_icd10"("icd_code") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "medical_encounters" ADD CONSTRAINT "FK_fb21b35bbed6cead5e8b96a6f80" FOREIGN KEY ("patient_id") REFERENCES "patient_profiles"("patient_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_encounters" ADD CONSTRAINT "FK_e85aa4d3098343e6ba571b7059c" FOREIGN KEY ("doctor_id") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_encounters" ADD CONSTRAINT "FK_f11b9babce0f2fef0d5ec9bef57" FOREIGN KEY ("assigned_room_id") REFERENCES "org_rooms"("room_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_encounters" ADD CONSTRAINT "FK_ead60871a4855f25e1c3c9b0261" FOREIGN KEY ("final_icd_code") REFERENCES "ref_icd10"("icd_code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_requests" ADD CONSTRAINT "FK_8a5d00fa172b47fd14338a30786" FOREIGN KEY ("encounter_id") REFERENCES "medical_encounters"("encounter_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_requests" ADD CONSTRAINT "FK_c86fb83cd9facc40fab94e90fcd" FOREIGN KEY ("requesting_doctor_id") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ref_service_categories" ADD CONSTRAINT "FK_3a47a94cf6c9ef7ff408cb5da81" FOREIGN KEY ("parent_id") REFERENCES "ref_service_categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ref_services" ADD CONSTRAINT "FK_d997a85ccf9bd123a13d792983e" FOREIGN KEY ("category_id") REFERENCES "ref_service_categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_request_items" ADD CONSTRAINT "FK_d89483fba694bc0b0f8e3b98330" FOREIGN KEY ("request_id") REFERENCES "service_requests"("request_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_request_items" ADD CONSTRAINT "FK_d008e7783ea85967e620232d981" FOREIGN KEY ("service_id") REFERENCES "ref_services"("service_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_report_templates" ADD CONSTRAINT "FK_bd6f065a6a0e1f8d57c6489fe83" FOREIGN KEY ("service_id") REFERENCES "ref_services"("service_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_report_templates" ADD CONSTRAINT "FK_48f7c1205ccbf7b3f1d3ad17fc9" FOREIGN KEY ("created_by") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_results" ADD CONSTRAINT "FK_cded0fbfa63d3cdf9e7d4b9c0a1" FOREIGN KEY ("request_item_id") REFERENCES "service_request_items"("item_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_results" ADD CONSTRAINT "FK_240c8a2358ff6730d0860300c79" FOREIGN KEY ("technician_id") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_results" ADD CONSTRAINT "FK_86688ee1acf6be226b2cd1bf4bb" FOREIGN KEY ("approving_doctor_id") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_results" ADD CONSTRAINT "FK_e767cd88327e09d203792ec09e5" FOREIGN KEY ("used_template_id") REFERENCES "service_report_templates"("template_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result_discussions" ADD CONSTRAINT "FK_f089c61da3f49c5520a76baa183" FOREIGN KEY ("result_id") REFERENCES "service_results"("result_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result_discussions" ADD CONSTRAINT "FK_4f5ce1e66b3dc1dade5d6534962" FOREIGN KEY ("sender_id") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result_discussions" ADD CONSTRAINT "FK_fc64c65eb2bbfb038acb3e48589" FOREIGN KEY ("parent_id") REFERENCES "result_discussions"("discussion_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_services" ADD CONSTRAINT "FK_4ddbbcc854aa78ba7b2b1f7942d" FOREIGN KEY ("room_id") REFERENCES "org_rooms"("room_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_services" ADD CONSTRAINT "FK_168cd7db85d0335cd8b659fa4b7" FOREIGN KEY ("service_id") REFERENCES "ref_services"("service_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result_images" ADD CONSTRAINT "FK_9fab27efd124cc82fe07c0ea774" FOREIGN KEY ("result_id") REFERENCES "service_results"("result_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result_images" ADD CONSTRAINT "FK_0b1cde11a25c2c481b7416da53d" FOREIGN KEY ("uploaded_by") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rel_service_indicators" ADD CONSTRAINT "FK_366bad4369e453ab6e1ecf4d4af" FOREIGN KEY ("service_id") REFERENCES "ref_services"("service_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "rel_service_indicators" ADD CONSTRAINT "FK_673a8142cf2c88d18c7ec37b9be" FOREIGN KEY ("indicator_id") REFERENCES "ref_lab_indicators"("indicator_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result_details_numeric" ADD CONSTRAINT "FK_a19153b52ac97ced7a30f8acd38" FOREIGN KEY ("result_id") REFERENCES "service_results"("result_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result_details_numeric" ADD CONSTRAINT "FK_ba716d62b548fcd6bfdcd75fe95" FOREIGN KEY ("indicator_id") REFERENCES "ref_lab_indicators"("indicator_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" ADD CONSTRAINT "FK_ff46ce7ef2e6fed3ba4322395a9" FOREIGN KEY ("encounter_id") REFERENCES "medical_encounters"("encounter_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" ADD CONSTRAINT "FK_70bcec25fe6985aceabb77152e7" FOREIGN KEY ("room_id") REFERENCES "org_rooms"("room_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queue_counters" ADD CONSTRAINT "FK_1af2fa53b6a7968b8cde9fb7ecf" FOREIGN KEY ("room_id") REFERENCES "org_rooms"("room_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ref_drug_categories" ADD CONSTRAINT "FK_9d9b49479e91093572afb25ecdf" FOREIGN KEY ("parent_id") REFERENCES "ref_drug_categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ref_drugs" ADD CONSTRAINT "FK_1f64061c355ed1bff14ccf3548d" FOREIGN KEY ("category_id") REFERENCES "ref_drug_categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescriptions" ADD CONSTRAINT "FK_f09b4189e7145df4fe7565246cc" FOREIGN KEY ("encounter_id") REFERENCES "medical_encounters"("encounter_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescriptions" ADD CONSTRAINT "FK_86a146a7fbf4c987c64f332e30d" FOREIGN KEY ("prescribing_doctor_id") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescriptions" ADD CONSTRAINT "FK_3119ecc3e3b63fabbbbc85f6720" FOREIGN KEY ("dispensing_pharmacist_id") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescription_details" ADD CONSTRAINT "FK_15ac2c0a760ba909742b38e2172" FOREIGN KEY ("prescription_id") REFERENCES "prescriptions"("prescription_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "prescription_details" ADD CONSTRAINT "FK_7fadbafc0f45378de76b45eee1b" FOREIGN KEY ("drug_id") REFERENCES "ref_drugs"("drug_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drug_imports" ADD CONSTRAINT "FK_f1f95c089351c58623a24a79cdf" FOREIGN KEY ("imported_by") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drug_import_details" ADD CONSTRAINT "FK_95280e3615d627b2af56beff039" FOREIGN KEY ("import_id") REFERENCES "drug_imports"("import_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "drug_import_details" ADD CONSTRAINT "FK_de1040240c908468203b2b2e025" FOREIGN KEY ("drug_id") REFERENCES "ref_drugs"("drug_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_d4d2daa5eafb9c88a55ed1c654f" FOREIGN KEY ("encounter_id") REFERENCES "medical_encounters"("encounter_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_c07224a78c1fd5dcd38e91284c5" FOREIGN KEY ("cashier_id") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_payments" ADD CONSTRAINT "FK_e94fa427d3da279450dba6f4aa6" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("invoice_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_payments" ADD CONSTRAINT "FK_71e86e2443a2e4997e177da8e0f" FOREIGN KEY ("payment_method_code") REFERENCES "ref_payment_methods"("payment_method_code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_dc991d555664682cfe892eea2c1" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("invoice_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_5e25c028d8232871f9ca5e5fc57" FOREIGN KEY ("service_item_id") REFERENCES "service_request_items"("item_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_items" ADD CONSTRAINT "FK_d62af2868369cf2439ffb3454d1" FOREIGN KEY ("prescription_detail_id") REFERENCES "prescription_details"("detail_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image_annotations" ADD CONSTRAINT "FK_8b565f0ccae41bb2f0dbbd75c0c" FOREIGN KEY ("image_id") REFERENCES "result_images"("image_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image_annotations" ADD CONSTRAINT "FK_85ccc13722395a81571042d9156" FOREIGN KEY ("labeled_by") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image_annotations" ADD CONSTRAINT "FK_1ce61e3181369a003b92ad6b9a1" FOREIGN KEY ("reviewed_by") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image_annotations" ADD CONSTRAINT "FK_c25a542133e48d8021a8c09c59f" FOREIGN KEY ("approved_by") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "annotation_projects" ADD CONSTRAINT "FK_578673b9bb1c2c290ea2592741b" FOREIGN KEY ("created_by") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "annotation_project_images" ADD CONSTRAINT "FK_d1a63f47f3dacd794f5046df2a6" FOREIGN KEY ("project_id") REFERENCES "annotation_projects"("project_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "annotation_project_images" ADD CONSTRAINT "FK_df13cb07873e18e14e4f6124abc" FOREIGN KEY ("image_id") REFERENCES "result_images"("image_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "annotation_project_images" ADD CONSTRAINT "FK_6f5210a1cb02261c4de8d70b8c0" FOREIGN KEY ("added_by") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "annotation_project_images" DROP CONSTRAINT "FK_6f5210a1cb02261c4de8d70b8c0"`);
        await queryRunner.query(`ALTER TABLE "annotation_project_images" DROP CONSTRAINT "FK_df13cb07873e18e14e4f6124abc"`);
        await queryRunner.query(`ALTER TABLE "annotation_project_images" DROP CONSTRAINT "FK_d1a63f47f3dacd794f5046df2a6"`);
        await queryRunner.query(`ALTER TABLE "annotation_projects" DROP CONSTRAINT "FK_578673b9bb1c2c290ea2592741b"`);
        await queryRunner.query(`ALTER TABLE "image_annotations" DROP CONSTRAINT "FK_c25a542133e48d8021a8c09c59f"`);
        await queryRunner.query(`ALTER TABLE "image_annotations" DROP CONSTRAINT "FK_1ce61e3181369a003b92ad6b9a1"`);
        await queryRunner.query(`ALTER TABLE "image_annotations" DROP CONSTRAINT "FK_85ccc13722395a81571042d9156"`);
        await queryRunner.query(`ALTER TABLE "image_annotations" DROP CONSTRAINT "FK_8b565f0ccae41bb2f0dbbd75c0c"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_d62af2868369cf2439ffb3454d1"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_5e25c028d8232871f9ca5e5fc57"`);
        await queryRunner.query(`ALTER TABLE "invoice_items" DROP CONSTRAINT "FK_dc991d555664682cfe892eea2c1"`);
        await queryRunner.query(`ALTER TABLE "invoice_payments" DROP CONSTRAINT "FK_71e86e2443a2e4997e177da8e0f"`);
        await queryRunner.query(`ALTER TABLE "invoice_payments" DROP CONSTRAINT "FK_e94fa427d3da279450dba6f4aa6"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_c07224a78c1fd5dcd38e91284c5"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_d4d2daa5eafb9c88a55ed1c654f"`);
        await queryRunner.query(`ALTER TABLE "drug_import_details" DROP CONSTRAINT "FK_de1040240c908468203b2b2e025"`);
        await queryRunner.query(`ALTER TABLE "drug_import_details" DROP CONSTRAINT "FK_95280e3615d627b2af56beff039"`);
        await queryRunner.query(`ALTER TABLE "drug_imports" DROP CONSTRAINT "FK_f1f95c089351c58623a24a79cdf"`);
        await queryRunner.query(`ALTER TABLE "prescription_details" DROP CONSTRAINT "FK_7fadbafc0f45378de76b45eee1b"`);
        await queryRunner.query(`ALTER TABLE "prescription_details" DROP CONSTRAINT "FK_15ac2c0a760ba909742b38e2172"`);
        await queryRunner.query(`ALTER TABLE "prescriptions" DROP CONSTRAINT "FK_3119ecc3e3b63fabbbbc85f6720"`);
        await queryRunner.query(`ALTER TABLE "prescriptions" DROP CONSTRAINT "FK_86a146a7fbf4c987c64f332e30d"`);
        await queryRunner.query(`ALTER TABLE "prescriptions" DROP CONSTRAINT "FK_f09b4189e7145df4fe7565246cc"`);
        await queryRunner.query(`ALTER TABLE "ref_drugs" DROP CONSTRAINT "FK_1f64061c355ed1bff14ccf3548d"`);
        await queryRunner.query(`ALTER TABLE "ref_drug_categories" DROP CONSTRAINT "FK_9d9b49479e91093572afb25ecdf"`);
        await queryRunner.query(`ALTER TABLE "queue_counters" DROP CONSTRAINT "FK_1af2fa53b6a7968b8cde9fb7ecf"`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" DROP CONSTRAINT "FK_70bcec25fe6985aceabb77152e7"`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" DROP CONSTRAINT "FK_ff46ce7ef2e6fed3ba4322395a9"`);
        await queryRunner.query(`ALTER TABLE "result_details_numeric" DROP CONSTRAINT "FK_ba716d62b548fcd6bfdcd75fe95"`);
        await queryRunner.query(`ALTER TABLE "result_details_numeric" DROP CONSTRAINT "FK_a19153b52ac97ced7a30f8acd38"`);
        await queryRunner.query(`ALTER TABLE "rel_service_indicators" DROP CONSTRAINT "FK_673a8142cf2c88d18c7ec37b9be"`);
        await queryRunner.query(`ALTER TABLE "rel_service_indicators" DROP CONSTRAINT "FK_366bad4369e453ab6e1ecf4d4af"`);
        await queryRunner.query(`ALTER TABLE "result_images" DROP CONSTRAINT "FK_0b1cde11a25c2c481b7416da53d"`);
        await queryRunner.query(`ALTER TABLE "result_images" DROP CONSTRAINT "FK_9fab27efd124cc82fe07c0ea774"`);
        await queryRunner.query(`ALTER TABLE "room_services" DROP CONSTRAINT "FK_168cd7db85d0335cd8b659fa4b7"`);
        await queryRunner.query(`ALTER TABLE "room_services" DROP CONSTRAINT "FK_4ddbbcc854aa78ba7b2b1f7942d"`);
        await queryRunner.query(`ALTER TABLE "result_discussions" DROP CONSTRAINT "FK_fc64c65eb2bbfb038acb3e48589"`);
        await queryRunner.query(`ALTER TABLE "result_discussions" DROP CONSTRAINT "FK_4f5ce1e66b3dc1dade5d6534962"`);
        await queryRunner.query(`ALTER TABLE "result_discussions" DROP CONSTRAINT "FK_f089c61da3f49c5520a76baa183"`);
        await queryRunner.query(`ALTER TABLE "service_results" DROP CONSTRAINT "FK_e767cd88327e09d203792ec09e5"`);
        await queryRunner.query(`ALTER TABLE "service_results" DROP CONSTRAINT "FK_86688ee1acf6be226b2cd1bf4bb"`);
        await queryRunner.query(`ALTER TABLE "service_results" DROP CONSTRAINT "FK_240c8a2358ff6730d0860300c79"`);
        await queryRunner.query(`ALTER TABLE "service_results" DROP CONSTRAINT "FK_cded0fbfa63d3cdf9e7d4b9c0a1"`);
        await queryRunner.query(`ALTER TABLE "service_report_templates" DROP CONSTRAINT "FK_48f7c1205ccbf7b3f1d3ad17fc9"`);
        await queryRunner.query(`ALTER TABLE "service_report_templates" DROP CONSTRAINT "FK_bd6f065a6a0e1f8d57c6489fe83"`);
        await queryRunner.query(`ALTER TABLE "service_request_items" DROP CONSTRAINT "FK_d008e7783ea85967e620232d981"`);
        await queryRunner.query(`ALTER TABLE "service_request_items" DROP CONSTRAINT "FK_d89483fba694bc0b0f8e3b98330"`);
        await queryRunner.query(`ALTER TABLE "ref_services" DROP CONSTRAINT "FK_d997a85ccf9bd123a13d792983e"`);
        await queryRunner.query(`ALTER TABLE "ref_service_categories" DROP CONSTRAINT "FK_3a47a94cf6c9ef7ff408cb5da81"`);
        await queryRunner.query(`ALTER TABLE "service_requests" DROP CONSTRAINT "FK_c86fb83cd9facc40fab94e90fcd"`);
        await queryRunner.query(`ALTER TABLE "service_requests" DROP CONSTRAINT "FK_8a5d00fa172b47fd14338a30786"`);
        await queryRunner.query(`ALTER TABLE "medical_encounters" DROP CONSTRAINT "FK_ead60871a4855f25e1c3c9b0261"`);
        await queryRunner.query(`ALTER TABLE "medical_encounters" DROP CONSTRAINT "FK_f11b9babce0f2fef0d5ec9bef57"`);
        await queryRunner.query(`ALTER TABLE "medical_encounters" DROP CONSTRAINT "FK_e85aa4d3098343e6ba571b7059c"`);
        await queryRunner.query(`ALTER TABLE "medical_encounters" DROP CONSTRAINT "FK_fb21b35bbed6cead5e8b96a6f80"`);
        await queryRunner.query(`ALTER TABLE "ref_icd10" DROP CONSTRAINT "FK_1f8549d688a778e335445c7f43c"`);
        await queryRunner.query(`ALTER TABLE "system_config" DROP CONSTRAINT "FK_674473bbaa9859ba7e7d9f7ea9e"`);
        await queryRunner.query(`ALTER TABLE "system_notifications" DROP CONSTRAINT "FK_4729e2a2eda3f5d226c5174e66f"`);
        await queryRunner.query(`ALTER TABLE "system_notifications" DROP CONSTRAINT "FK_0d846fbfc20a6cb6fe06e61b41e"`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" DROP CONSTRAINT "FK_3f82683aa41853a895289b18d0d"`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" DROP CONSTRAINT "FK_cb1a0b04899905a2d423ed4b2ee"`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" DROP CONSTRAINT "FK_202fa10b67fa2a55f4c53b704ed"`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" DROP CONSTRAINT "FK_4f32f1a897f75bafed4199fb0bf"`);
        await queryRunner.query(`ALTER TABLE "patient_profiles" DROP CONSTRAINT "FK_93e9bd4212c9d779fb8b4398bd7"`);
        await queryRunner.query(`DROP TABLE "annotation_project_images"`);
        await queryRunner.query(`DROP TABLE "annotation_projects"`);
        await queryRunner.query(`DROP TYPE "public"."annotation_projects_task_type_enum"`);
        await queryRunner.query(`DROP TABLE "image_annotations"`);
        await queryRunner.query(`DROP TYPE "public"."image_annotations_annotation_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."image_annotations_annotation_source_enum"`);
        await queryRunner.query(`DROP TABLE "invoice_items"`);
        await queryRunner.query(`DROP TYPE "public"."invoice_items_item_type_enum"`);
        await queryRunner.query(`DROP TABLE "invoice_payments"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP TABLE "drug_import_details"`);
        await queryRunner.query(`DROP TABLE "ref_payment_methods"`);
        await queryRunner.query(`DROP TABLE "drug_imports"`);
        await queryRunner.query(`DROP TABLE "prescription_details"`);
        await queryRunner.query(`DROP TABLE "prescriptions"`);
        await queryRunner.query(`DROP TYPE "public"."prescriptions_status_enum"`);
        await queryRunner.query(`DROP TABLE "ref_drugs"`);
        await queryRunner.query(`DROP TABLE "ref_drug_categories"`);
        await queryRunner.query(`DROP INDEX "public"."uq_counter_room_type_day"`);
        await queryRunner.query(`DROP TABLE "queue_counters"`);
        await queryRunner.query(`DROP TYPE "public"."queue_counters_ticket_type_enum"`);
        await queryRunner.query(`DROP TABLE "queue_tickets"`);
        await queryRunner.query(`DROP TYPE "public"."queue_tickets_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."queue_tickets_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."queue_tickets_ticket_type_enum"`);
        await queryRunner.query(`DROP TABLE "result_details_numeric"`);
        await queryRunner.query(`DROP TABLE "rel_service_indicators"`);
        await queryRunner.query(`DROP TABLE "ref_lab_indicators"`);
        await queryRunner.query(`DROP TABLE "result_images"`);
        await queryRunner.query(`DROP TABLE "room_services"`);
        await queryRunner.query(`DROP TABLE "result_discussions"`);
        await queryRunner.query(`DROP TABLE "service_results"`);
        await queryRunner.query(`DROP TABLE "service_report_templates"`);
        await queryRunner.query(`DROP TABLE "service_request_items"`);
        await queryRunner.query(`DROP TABLE "ref_services"`);
        await queryRunner.query(`DROP TYPE "public"."ref_services_result_input_type_enum"`);
        await queryRunner.query(`DROP TABLE "ref_service_categories"`);
        await queryRunner.query(`DROP TABLE "service_requests"`);
        await queryRunner.query(`DROP TYPE "public"."service_requests_payment_status_enum"`);
        await queryRunner.query(`DROP TABLE "medical_encounters"`);
        await queryRunner.query(`DROP TYPE "public"."medical_encounters_current_status_enum"`);
        await queryRunner.query(`DROP TABLE "ref_icd10"`);
        await queryRunner.query(`DROP TABLE "system_audit_logs"`);
        await queryRunner.query(`DROP TABLE "system_config"`);
        await queryRunner.query(`DROP TABLE "system_notifications"`);
        await queryRunner.query(`DROP TYPE "public"."system_notifications_notification_type_enum"`);
        await queryRunner.query(`DROP TABLE "staff_profiles"`);
        await queryRunner.query(`DROP TABLE "ref_specialties"`);
        await queryRunner.query(`DROP TABLE "org_rooms"`);
        await queryRunner.query(`DROP TYPE "public"."org_rooms_room_type_enum"`);
        await queryRunner.query(`DROP TABLE "sys_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71f921cdd2a2d68e7825152c68"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_466c22a61fbc6141d7b064cbed"`);
        await queryRunner.query(`DROP TABLE "sys_users"`);
        await queryRunner.query(`DROP TABLE "patient_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."patient_profiles_gender_enum"`);
    }

}
