import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1766087666794 implements MigrationInterface {
    name = 'Init1766087666794'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "sys_roles" ("role_id" SERIAL NOT NULL, "role_code" character varying(50) NOT NULL, "role_name" character varying(100), "description" text, CONSTRAINT "UQ_d50f63eff3ee563a92cdca56bf6" UNIQUE ("role_code"), CONSTRAINT "PK_b94678bcefe1a557ed67613bbfa" PRIMARY KEY ("role_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."org_rooms_room_type_enum" AS ENUM('CLINIC', 'PARACLINICAL', 'PHARMACY', 'CASHIER', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "org_rooms" ("room_id" SERIAL NOT NULL, "room_name" character varying(100) NOT NULL, "room_type" "public"."org_rooms_room_type_enum", "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_f76b9aae085d880b9b27ce208c8" PRIMARY KEY ("room_id"))`);
        await queryRunner.query(`CREATE TABLE "ref_specialties" ("specialty_id" SERIAL NOT NULL, "specialty_code" character varying(50) NOT NULL, "specialty_name" character varying(255) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "UQ_957c6df5382e1b12df47b51157f" UNIQUE ("specialty_code"), CONSTRAINT "PK_3efcc291a06a2f0e2ca2204e9c8" PRIMARY KEY ("specialty_id"))`);
        await queryRunner.query(`CREATE TABLE "staff_profiles" ("staff_id" uuid NOT NULL, "role_id" integer NOT NULL, "assigned_room_id" integer, "specialty_id" integer, "full_name" character varying(255) NOT NULL, "signature_url" character varying(500), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_4f32f1a897f75bafed4199fb0bf" PRIMARY KEY ("staff_id"))`);
        await queryRunner.query(`CREATE TABLE "sys_users" ("user_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying(100), "password" character varying(255), "email" character varying(150), "phone" character varying(20), "cccd" character varying(12), "is_active" boolean NOT NULL DEFAULT true, "refresh_token_hash" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_466c22a61fbc6141d7b064cbed4" UNIQUE ("username"), CONSTRAINT "UQ_71f921cdd2a2d68e7825152c684" UNIQUE ("cccd"), CONSTRAINT "PK_360c27699169a865b1c7aa6f8d7" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_466c22a61fbc6141d7b064cbed" ON "sys_users" ("username") `);
        await queryRunner.query(`CREATE INDEX "IDX_71f921cdd2a2d68e7825152c68" ON "sys_users" ("cccd") `);
        await queryRunner.query(`CREATE TYPE "public"."patient_profiles_gender_enum" AS ENUM('NAM', 'NU', 'KHAC')`);
        await queryRunner.query(`CREATE TABLE "patient_profiles" ("patient_id" uuid NOT NULL, "full_name" character varying(255) NOT NULL, "dob" date NOT NULL, "gender" "public"."patient_profiles_gender_enum" NOT NULL, "address" text, "medical_history" text, "allergy_history" text, "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_93e9bd4212c9d779fb8b4398bd7" PRIMARY KEY ("patient_id"))`);
        await queryRunner.query(`CREATE TABLE "ref_icd10" ("icd_code" character varying(10) NOT NULL, "parent_code" character varying(10), "name_vi" character varying(500) NOT NULL, "name_en" character varying(500), "level" integer, "is_leaf" boolean NOT NULL DEFAULT false, "active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_ab183b9cc9e377cb84f114e7449" PRIMARY KEY ("icd_code"))`);
        await queryRunner.query(`CREATE TYPE "public"."medical_encounters_current_status_enum" AS ENUM('REGISTERED', 'AWAITING_PAYMENT', 'IN_CONSULTATION', 'AWAITING_CLS', 'IN_CLS', 'CLS_COMPLETED', 'RESULTS_READY', 'COMPLETED')`);
        await queryRunner.query(`CREATE TABLE "medical_encounters" ("encounter_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "patient_id" uuid, "doctor_id" uuid, "assigned_room_id" integer, "final_icd_code" character varying(10), "visit_date" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "current_status" "public"."medical_encounters_current_status_enum" NOT NULL DEFAULT 'REGISTERED', "initial_symptoms" text, "weight" numeric(5,2), "height" numeric(5,2), "bmi" numeric(4,2), "temperature" numeric(4,1), "pulse" integer, "respiratory_rate" integer, "bp_systolic" integer, "bp_diastolic" integer, "sp_o2" numeric(5,2), "doctor_conclusion" text, "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_2a840667ef58abb1f90226ab28b" PRIMARY KEY ("encounter_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."service_requests_payment_status_enum" AS ENUM('UNPAID', 'PARTIALLY_PAID', 'PAID', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "service_requests" ("request_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "encounter_id" uuid, "requesting_doctor_id" uuid, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "payment_status" "public"."service_requests_payment_status_enum" NOT NULL DEFAULT 'UNPAID', "notes" text, "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_f01ec4a8e6bb19cc88f80aa835d" PRIMARY KEY ("request_id"))`);
        await queryRunner.query(`CREATE TABLE "ref_service_categories" ("category_id" SERIAL NOT NULL, "parent_id" integer, "category_name" character varying(255) NOT NULL, "is_system_root" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_9ff47e4cede15f0e081fc94265d" PRIMARY KEY ("category_id"))`);
        await queryRunner.query(`CREATE TABLE "ref_services" ("service_id" SERIAL NOT NULL, "category_id" integer, "service_name" character varying(255) NOT NULL, "unit_price" numeric(15,2), CONSTRAINT "PK_ebbef22eb39f6d8ea2eb9cbbcc8" PRIMARY KEY ("service_id"))`);
        await queryRunner.query(`CREATE TABLE "service_request_items" ("item_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "request_id" uuid, "service_id" integer, CONSTRAINT "PK_8e7b53337e0bf4c0484e81dcd13" PRIMARY KEY ("item_id"))`);
        await queryRunner.query(`CREATE TABLE "service_results" ("result_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "request_item_id" uuid, "technician_id" uuid, "main_conclusion" text, "report_body_html" text, "is_abnormal" boolean NOT NULL DEFAULT false, "result_time" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_db0e4c29e1fd7b7a3b7a9ac7562" PRIMARY KEY ("result_id"))`);
        await queryRunner.query(`CREATE TABLE "result_images" ("image_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "result_id" uuid, "uploaded_by" uuid, "public_id" character varying(255), "original_image_url" character varying(500) NOT NULL, "file_name" character varying(255), "file_size" bigint, "mime_type" character varying(100), "uploaded_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a746d6b44498251b6e9ca3fcc1a" PRIMARY KEY ("image_id"))`);
        await queryRunner.query(`CREATE TABLE "room_services" ("room_id" integer NOT NULL, "service_id" integer NOT NULL, CONSTRAINT "PK_dac4ce50107d88ad7bce51fe61b" PRIMARY KEY ("room_id", "service_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."queue_tickets_ticket_type_enum" AS ENUM('REGISTRATION', 'CONSULTATION', 'SERVICE')`);
        await queryRunner.query(`CREATE TYPE "public"."queue_tickets_source_enum" AS ENUM('ONLINE', 'WALKIN')`);
        await queryRunner.query(`CREATE TYPE "public"."queue_tickets_status_enum" AS ENUM('WAITING', 'CALLED', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED')`);
        await queryRunner.query(`CREATE TABLE "queue_tickets" ("ticket_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "encounter_id" uuid, "room_id" integer NOT NULL, "ticket_type" "public"."queue_tickets_ticket_type_enum" NOT NULL, "display_number" integer NOT NULL, "source" "public"."queue_tickets_source_enum" NOT NULL DEFAULT 'WALKIN', "status" "public"."queue_tickets_status_enum" NOT NULL DEFAULT 'WAITING', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "called_at" TIMESTAMP WITH TIME ZONE, "started_at" TIMESTAMP WITH TIME ZONE, "service_ids" integer array, "completed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_e573582e059b4043f3275aecead" PRIMARY KEY ("ticket_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."queue_counters_ticket_type_enum" AS ENUM('REGISTRATION', 'CONSULTATION', 'SERVICE')`);
        await queryRunner.query(`CREATE TABLE "queue_counters" ("counter_id" SERIAL NOT NULL, "room_id" integer NOT NULL, "ticket_type" "public"."queue_counters_ticket_type_enum" NOT NULL, "last_number" integer NOT NULL DEFAULT '0', "reset_date" date NOT NULL DEFAULT ('now'::text)::date, CONSTRAINT "PK_d55dbbc8a94c8f6b4ecf704e4e7" PRIMARY KEY ("counter_id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_counter_room_type_day" ON "queue_counters" ("room_id", "ticket_type", "reset_date") `);
        await queryRunner.query(`CREATE TYPE "public"."image_annotations_annotation_source_enum" AS ENUM('AI', 'HUMAN')`);
        await queryRunner.query(`CREATE TYPE "public"."image_annotations_annotation_status_enum" AS ENUM('IN_PROGRESS', 'SUBMITTED', 'APPROVED', 'REJECTED', 'DEPRECATED')`);
        await queryRunner.query(`CREATE TABLE "image_annotations" ("annotation_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "image_id" uuid NOT NULL, "labeled_by" uuid, "reviewed_by" uuid, "approved_by" uuid, "annotation_source" "public"."image_annotations_annotation_source_enum" NOT NULL, "annotation_data" jsonb NOT NULL, "ai_model_name" character varying(100), "ai_model_version" character varying(50), "labeled_at" TIMESTAMP WITH TIME ZONE, "reviewed_at" TIMESTAMP WITH TIME ZONE, "approved_at" TIMESTAMP WITH TIME ZONE, "annotation_status" "public"."image_annotations_annotation_status_enum" NOT NULL DEFAULT 'IN_PROGRESS', "rejection_reason" text, "deprecation_reason" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_fb3df6efc4e13e2e9d35e97afbc" PRIMARY KEY ("annotation_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."annotation_projects_task_type_enum" AS ENUM('CLASSIFICATION', 'BOUNDING_BOX', 'SEGMENTATION', 'KEYPOINT', 'OCR', 'OTHER')`);
        await queryRunner.query(`CREATE TABLE "annotation_projects" ("project_id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_by" uuid, "name" character varying(255) NOT NULL, "description" text, "task_type" "public"."annotation_projects_task_type_enum" NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bfcf1c8bb3fd31f0a23c7fe6ec" PRIMARY KEY ("project_id"))`);
        await queryRunner.query(`CREATE TABLE "annotation_project_images" ("project_id" uuid NOT NULL, "image_id" uuid NOT NULL, "added_by" uuid, "added_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_d68f68a6f34f807a5e694943d84" PRIMARY KEY ("project_id", "image_id"))`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" ADD CONSTRAINT "FK_4f32f1a897f75bafed4199fb0bf" FOREIGN KEY ("staff_id") REFERENCES "sys_users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" ADD CONSTRAINT "FK_202fa10b67fa2a55f4c53b704ed" FOREIGN KEY ("role_id") REFERENCES "sys_roles"("role_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" ADD CONSTRAINT "FK_cb1a0b04899905a2d423ed4b2ee" FOREIGN KEY ("assigned_room_id") REFERENCES "org_rooms"("room_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" ADD CONSTRAINT "FK_3f82683aa41853a895289b18d0d" FOREIGN KEY ("specialty_id") REFERENCES "ref_specialties"("specialty_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "patient_profiles" ADD CONSTRAINT "FK_93e9bd4212c9d779fb8b4398bd7" FOREIGN KEY ("patient_id") REFERENCES "sys_users"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ref_icd10" ADD CONSTRAINT "FK_1f8549d688a778e335445c7f43c" FOREIGN KEY ("parent_code") REFERENCES "ref_icd10"("icd_code") ON DELETE NO ACTION ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "medical_encounters" ADD CONSTRAINT "FK_fb21b35bbed6cead5e8b96a6f80" FOREIGN KEY ("patient_id") REFERENCES "patient_profiles"("patient_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_encounters" ADD CONSTRAINT "FK_e85aa4d3098343e6ba571b7059c" FOREIGN KEY ("doctor_id") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_encounters" ADD CONSTRAINT "FK_f11b9babce0f2fef0d5ec9bef57" FOREIGN KEY ("assigned_room_id") REFERENCES "org_rooms"("room_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "medical_encounters" ADD CONSTRAINT "FK_ead60871a4855f25e1c3c9b0261" FOREIGN KEY ("final_icd_code") REFERENCES "ref_icd10"("icd_code") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_requests" ADD CONSTRAINT "FK_8a5d00fa172b47fd14338a30786" FOREIGN KEY ("encounter_id") REFERENCES "medical_encounters"("encounter_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_requests" ADD CONSTRAINT "FK_c86fb83cd9facc40fab94e90fcd" FOREIGN KEY ("requesting_doctor_id") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ref_service_categories" ADD CONSTRAINT "FK_3a47a94cf6c9ef7ff408cb5da81" FOREIGN KEY ("parent_id") REFERENCES "ref_service_categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ref_services" ADD CONSTRAINT "FK_d997a85ccf9bd123a13d792983e" FOREIGN KEY ("category_id") REFERENCES "ref_service_categories"("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_request_items" ADD CONSTRAINT "FK_d89483fba694bc0b0f8e3b98330" FOREIGN KEY ("request_id") REFERENCES "service_requests"("request_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_request_items" ADD CONSTRAINT "FK_d008e7783ea85967e620232d981" FOREIGN KEY ("service_id") REFERENCES "ref_services"("service_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_results" ADD CONSTRAINT "FK_cded0fbfa63d3cdf9e7d4b9c0a1" FOREIGN KEY ("request_item_id") REFERENCES "service_request_items"("item_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "service_results" ADD CONSTRAINT "FK_240c8a2358ff6730d0860300c79" FOREIGN KEY ("technician_id") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result_images" ADD CONSTRAINT "FK_9fab27efd124cc82fe07c0ea774" FOREIGN KEY ("result_id") REFERENCES "service_results"("result_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "result_images" ADD CONSTRAINT "FK_0b1cde11a25c2c481b7416da53d" FOREIGN KEY ("uploaded_by") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_services" ADD CONSTRAINT "FK_4ddbbcc854aa78ba7b2b1f7942d" FOREIGN KEY ("room_id") REFERENCES "org_rooms"("room_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "room_services" ADD CONSTRAINT "FK_168cd7db85d0335cd8b659fa4b7" FOREIGN KEY ("service_id") REFERENCES "ref_services"("service_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" ADD CONSTRAINT "FK_ff46ce7ef2e6fed3ba4322395a9" FOREIGN KEY ("encounter_id") REFERENCES "medical_encounters"("encounter_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" ADD CONSTRAINT "FK_70bcec25fe6985aceabb77152e7" FOREIGN KEY ("room_id") REFERENCES "org_rooms"("room_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "queue_counters" ADD CONSTRAINT "FK_1af2fa53b6a7968b8cde9fb7ecf" FOREIGN KEY ("room_id") REFERENCES "org_rooms"("room_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image_annotations" ADD CONSTRAINT "FK_8b565f0ccae41bb2f0dbbd75c0c" FOREIGN KEY ("image_id") REFERENCES "result_images"("image_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image_annotations" ADD CONSTRAINT "FK_85ccc13722395a81571042d9156" FOREIGN KEY ("labeled_by") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image_annotations" ADD CONSTRAINT "FK_1ce61e3181369a003b92ad6b9a1" FOREIGN KEY ("reviewed_by") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "image_annotations" ADD CONSTRAINT "FK_c25a542133e48d8021a8c09c59f" FOREIGN KEY ("approved_by") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "annotation_projects" ADD CONSTRAINT "FK_578673b9bb1c2c290ea2592741b" FOREIGN KEY ("created_by") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "annotation_project_images" ADD CONSTRAINT "FK_d1a63f47f3dacd794f5046df2a6" FOREIGN KEY ("project_id") REFERENCES "annotation_projects"("project_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "annotation_project_images" ADD CONSTRAINT "FK_df13cb07873e18e14e4f6124abc" FOREIGN KEY ("image_id") REFERENCES "result_images"("image_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "annotation_project_images" ADD CONSTRAINT "FK_6f5210a1cb02261c4de8d70b8c0" FOREIGN KEY ("added_by") REFERENCES "staff_profiles"("staff_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "annotation_project_images" DROP CONSTRAINT "FK_6f5210a1cb02261c4de8d70b8c0"`);
        await queryRunner.query(`ALTER TABLE "annotation_project_images" DROP CONSTRAINT "FK_df13cb07873e18e14e4f6124abc"`);
        await queryRunner.query(`ALTER TABLE "annotation_project_images" DROP CONSTRAINT "FK_d1a63f47f3dacd794f5046df2a6"`);
        await queryRunner.query(`ALTER TABLE "annotation_projects" DROP CONSTRAINT "FK_578673b9bb1c2c290ea2592741b"`);
        await queryRunner.query(`ALTER TABLE "image_annotations" DROP CONSTRAINT "FK_c25a542133e48d8021a8c09c59f"`);
        await queryRunner.query(`ALTER TABLE "image_annotations" DROP CONSTRAINT "FK_1ce61e3181369a003b92ad6b9a1"`);
        await queryRunner.query(`ALTER TABLE "image_annotations" DROP CONSTRAINT "FK_85ccc13722395a81571042d9156"`);
        await queryRunner.query(`ALTER TABLE "image_annotations" DROP CONSTRAINT "FK_8b565f0ccae41bb2f0dbbd75c0c"`);
        await queryRunner.query(`ALTER TABLE "queue_counters" DROP CONSTRAINT "FK_1af2fa53b6a7968b8cde9fb7ecf"`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" DROP CONSTRAINT "FK_70bcec25fe6985aceabb77152e7"`);
        await queryRunner.query(`ALTER TABLE "queue_tickets" DROP CONSTRAINT "FK_ff46ce7ef2e6fed3ba4322395a9"`);
        await queryRunner.query(`ALTER TABLE "room_services" DROP CONSTRAINT "FK_168cd7db85d0335cd8b659fa4b7"`);
        await queryRunner.query(`ALTER TABLE "room_services" DROP CONSTRAINT "FK_4ddbbcc854aa78ba7b2b1f7942d"`);
        await queryRunner.query(`ALTER TABLE "result_images" DROP CONSTRAINT "FK_0b1cde11a25c2c481b7416da53d"`);
        await queryRunner.query(`ALTER TABLE "result_images" DROP CONSTRAINT "FK_9fab27efd124cc82fe07c0ea774"`);
        await queryRunner.query(`ALTER TABLE "service_results" DROP CONSTRAINT "FK_240c8a2358ff6730d0860300c79"`);
        await queryRunner.query(`ALTER TABLE "service_results" DROP CONSTRAINT "FK_cded0fbfa63d3cdf9e7d4b9c0a1"`);
        await queryRunner.query(`ALTER TABLE "service_request_items" DROP CONSTRAINT "FK_d008e7783ea85967e620232d981"`);
        await queryRunner.query(`ALTER TABLE "service_request_items" DROP CONSTRAINT "FK_d89483fba694bc0b0f8e3b98330"`);
        await queryRunner.query(`ALTER TABLE "ref_services" DROP CONSTRAINT "FK_d997a85ccf9bd123a13d792983e"`);
        await queryRunner.query(`ALTER TABLE "ref_service_categories" DROP CONSTRAINT "FK_3a47a94cf6c9ef7ff408cb5da81"`);
        await queryRunner.query(`ALTER TABLE "service_requests" DROP CONSTRAINT "FK_c86fb83cd9facc40fab94e90fcd"`);
        await queryRunner.query(`ALTER TABLE "service_requests" DROP CONSTRAINT "FK_8a5d00fa172b47fd14338a30786"`);
        await queryRunner.query(`ALTER TABLE "medical_encounters" DROP CONSTRAINT "FK_ead60871a4855f25e1c3c9b0261"`);
        await queryRunner.query(`ALTER TABLE "medical_encounters" DROP CONSTRAINT "FK_f11b9babce0f2fef0d5ec9bef57"`);
        await queryRunner.query(`ALTER TABLE "medical_encounters" DROP CONSTRAINT "FK_e85aa4d3098343e6ba571b7059c"`);
        await queryRunner.query(`ALTER TABLE "medical_encounters" DROP CONSTRAINT "FK_fb21b35bbed6cead5e8b96a6f80"`);
        await queryRunner.query(`ALTER TABLE "ref_icd10" DROP CONSTRAINT "FK_1f8549d688a778e335445c7f43c"`);
        await queryRunner.query(`ALTER TABLE "patient_profiles" DROP CONSTRAINT "FK_93e9bd4212c9d779fb8b4398bd7"`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" DROP CONSTRAINT "FK_3f82683aa41853a895289b18d0d"`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" DROP CONSTRAINT "FK_cb1a0b04899905a2d423ed4b2ee"`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" DROP CONSTRAINT "FK_202fa10b67fa2a55f4c53b704ed"`);
        await queryRunner.query(`ALTER TABLE "staff_profiles" DROP CONSTRAINT "FK_4f32f1a897f75bafed4199fb0bf"`);
        await queryRunner.query(`DROP TABLE "annotation_project_images"`);
        await queryRunner.query(`DROP TABLE "annotation_projects"`);
        await queryRunner.query(`DROP TYPE "public"."annotation_projects_task_type_enum"`);
        await queryRunner.query(`DROP TABLE "image_annotations"`);
        await queryRunner.query(`DROP TYPE "public"."image_annotations_annotation_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."image_annotations_annotation_source_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uq_counter_room_type_day"`);
        await queryRunner.query(`DROP TABLE "queue_counters"`);
        await queryRunner.query(`DROP TYPE "public"."queue_counters_ticket_type_enum"`);
        await queryRunner.query(`DROP TABLE "queue_tickets"`);
        await queryRunner.query(`DROP TYPE "public"."queue_tickets_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."queue_tickets_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."queue_tickets_ticket_type_enum"`);
        await queryRunner.query(`DROP TABLE "room_services"`);
        await queryRunner.query(`DROP TABLE "result_images"`);
        await queryRunner.query(`DROP TABLE "service_results"`);
        await queryRunner.query(`DROP TABLE "service_request_items"`);
        await queryRunner.query(`DROP TABLE "ref_services"`);
        await queryRunner.query(`DROP TABLE "ref_service_categories"`);
        await queryRunner.query(`DROP TABLE "service_requests"`);
        await queryRunner.query(`DROP TYPE "public"."service_requests_payment_status_enum"`);
        await queryRunner.query(`DROP TABLE "medical_encounters"`);
        await queryRunner.query(`DROP TYPE "public"."medical_encounters_current_status_enum"`);
        await queryRunner.query(`DROP TABLE "ref_icd10"`);
        await queryRunner.query(`DROP TABLE "patient_profiles"`);
        await queryRunner.query(`DROP TYPE "public"."patient_profiles_gender_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71f921cdd2a2d68e7825152c68"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_466c22a61fbc6141d7b064cbed"`);
        await queryRunner.query(`DROP TABLE "sys_users"`);
        await queryRunner.query(`DROP TABLE "staff_profiles"`);
        await queryRunner.query(`DROP TABLE "ref_specialties"`);
        await queryRunner.query(`DROP TABLE "org_rooms"`);
        await queryRunner.query(`DROP TYPE "public"."org_rooms_room_type_enum"`);
        await queryRunner.query(`DROP TABLE "sys_roles"`);
    }

}
